# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  username: test
  password: changeme
  first_name: Test
  last_name: User
  date_of_birth: 25/12/1980
  secret_key_base: e6d95979b46495099e732576292a79b858883365e928a45c81633d0906d7a165583cc2e172e5348f0809c92e12819f6db28906cc2a58cc5cd6f27a45daaaa725

test:
  secret_key_base: 39f6ea3cde5b2f99ef4a5958d1e53100492a58d9d2a467aa8e1c8dd16e429e794a477e008dc7c274d1d42d13b37367a726d6f59a275b9cf122117b079da62ea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>
  first_name: <%= ENV["FIRST_NAME"] %>
  last_name: <%= ENV["LAST_NAME"] %>
  date_of_birth: <%= ENV["DATE_OF_BIRTH"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
